name: Build and Deploy Flask Docker App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout repo
      uses: actions/checkout@v3

    - name:  Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name:  Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name:  Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: devopsbabu16/flask-docker-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name:  SSH into EC2 and restart container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull devopsbabu16/flask-docker-app:latest
          docker stop flask-docker || true
          docker rm flask-docker || true
          docker run -d -p 5000:5000 --name flask-docker devopsbabu16/flask-docker-app:latest
